// https://leetcode.com/problems/find-the-difference
// 
// 
// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.
// Example:
// 
// Input:
// s = "abcd"
// t = "abcde"
// 
// Output:
// e
// 
// Explanation:
// 'e' is the letter that was added.
// 
public class Solution {
    public char findTheDifference(String s, String t) {
        char[] ch1 = s.toCharArray();
        char[] ch2 = t.toCharArray();
        char answer = 0;
        for (int i = 0; i < ch2.length; i++) {
            answer += ch2[i];
        }
        for (int i = 0; i < ch1.length; i++) {
            answer -= ch1[i];
        }
        return answer;
    }
}
